"""Phrase bank for the roast engine.

Each list should contain short, punchy lines that can be stitched together
with league stats. Phrases should remain under 140 characters to keep the
final blurb tight when the templates add stats around them.
"""
from __future__ import annotations

from typing import Dict, List

PHRASE_BANK: Dict[str, List[str]] = {
    # Dumpster Fire tiers (worst scores first)
    "dumpster_fire_tier1": [
        "lit the lineup on fire and then roasted marshmallows in the ashes",
        "left more empty possessions than a preseason scrimmage",
        "treated the salary cap like a tip jar—no change, no impact",
        "fumbled the remote before RedZone even kicked off",
        "built a DFS museum: lots of plaques, zero live exhibits",
        "checked the ceiling for leaks while the scoreboard caved in",
        "posted a rerun from 2019 and hoped nobody noticed",
        "chalked up zeros like it was a team-building exercise",
        "took a victory lap for clearing double digits—barely",
        "thought the bye week was a playable lineup option",
        "wrote a missing persons report for their own studs",
        "left the group chat on read after the second slate",
    ],
    "dumpster_fire_tier2": [
        "couldn’t decide between rebuilding and tanking, so did both",
        "kept the bench hydrated while the starters air-balled",
        "mailed in waivers with postage due",
        "turned lineup decisions into a choose-your-own L adventure",
        "let the spreadsheet auto-fill an obituary",
        "stuck in neutral while everyone else found overdrive",
        "got lapped by teams still setting alarms",
        "treated ceiling plays like they were ceiling fans",
        "packed the lineup with vibes and forgot production",
        "called a team meeting in the third quarter of RedZone",
        "spent more time trash talking than game planning",
        "brought a brunch menu to a bar fight",
    ],
    "dumpster_fire_tier3": [
        "is still searching for the panic button under the depth chart",
        "kept the training wheels on while the league popped wheelies",
        "ran the two-minute drill in slow motion",
        "keeps yelling ‘trust the process’ with no receipts",
        "played prevent defense against their own upside",
        "watched the matchup from the concourse",
        "showed up fashionably late and left fashionably beaten",
        "treated upside like a rumor and floor like a myth",
        "made more excuses than adjustments",
        "kept receipts, returned wins",
        "hid behind projections while reality threw flags",
        "left the spark in the group chat instead of the lineup",
    ],
    # Fraud Watch
    "fraud_watch": [
        "is running a Ponzi scheme with victory points",
        "stocks their trophy case with Funko Pops",
        "keeps winning coin flips while punting talent",
        "lives off narrative podcasts instead of box scores",
        "inflates the record like a crypto NFT",
        "hangs banners made of construction paper",
        "is running on vibes, caffeine, and opponent injuries",
        "keeps cashing checks written by soft matchups",
        "schedules parades before locking lineups",
        "has more luck than a Vegas residency",
        "sells hope the way influencers sell detox tea",
        "wants strength of schedule graded on a curve",
    ],
    # VP Crime Scene
    "vp_crime_scene_villain": [
        "left the bubble team bleeding VP on the floor",
        "kicked in the door, grabbed the VP stack, and vanished",
        "signed the crime scene tape in permanent marker",
        "treated decimal scoring like a burglary tool",
        "brought ski masks to the standings table",
        "ran a full heist and framed variance for the job",
        "stuffed the getaway bag with someone else’s VP",
        "stole lunch money and the lunch table",
        "left cleat marks all over the velvet rope",
        "had the audacity to celebrate at the chalk outline",
        "waved to security on the way out with the 2.5 VP",
        "stared the bubble squad in the eyes while jacking VP",
    ],
    "vp_crime_scene_victim": [
        "caught the bad beat and the medical bill",
        "filed a police report that came back ‘variance’",
        "watched VP evaporate like a free trial",
        "is still replaying the decimal where it all slipped",
        "let the villain walk off with their bar tab",
        "held the rope, missed the door",
        "took the punch, paid the cover charge",
        "is lawyering up against scoreboard malpractice",
        "needs grief counseling and a new kicker",
        "stared at the standings like a crime victim lineup",
        "is still scrubbing chalk dust off the jersey",
        "woke up to footprints across their VP column",
    ],
    # Spotlight
    "shit_talk_spotlight_alpha": [
        "pounded the slate like it owed rent",
        "spiked the clipboard and the projections",
        "dropped a mixtape on the standings page",
        "turned leverage picks into a guided missile",
        "treated chalk like seasoning, not a diet",
        "called their shot and hit the mezzanine",
        "ran hot enough to melt the waiver wire",
        "turned the group chat into a press conference",
        "hung a banner mid-Monday night",
        "made the league eat screenshots",
        "rewrote the matchup recap in all caps",
        "unplugged the opponent’s router with raw points",
    ],
    "shit_talk_spotlight_beta": [
        "took the mic and swallowed it whole",
        "got dunked on so hard the rim bent",
        "ran out of comebacks before kickoff",
        "brought memos to a fistfight",
        "needed the mercy rule and a hug",
        "played possum and forgot to wake up",
        "ate chalk and called it a cheat day",
        "walked into a sweep with slippers on",
        "is learning humility via push notification",
        "took the group chat L without logging in",
        "left the receipts at home and the score at 70",
        "responded to a haymaker with a shrug",
    ],
    # Values & Busts
    "value_pop": [
        "found coupons that scanned for touchdowns",
        "dug a flex gem out of the clearance bin",
        "cooked a gourmet lineup with leftovers",
        "turned Sunday sweat into thrift store gold",
        "drafted DFS poetry on a ramen budget",
        "raided the bargain rack like a Black Friday vet",
        "turned waiver dust into fireworks",
        "treated low salary like insider trading",
        "turned contrarian darts into center mass",
        "whispered sweet nothings to leverage plays",
        "smuggled ceiling through customs in a value hoodie",
        "printed green screens with couch cushion coins",
    ],
    "value_bust": [
        "burned salary like an arsonist with a matchbook",
        "paid premium for three yards and cloud of tears",
        "stuffed chalk into the lineup like it was cash",
        "maxed the card on name brands with no stats",
        "trusted the projections and got a trust fall",
        "left champagne bottles filled with flat soda",
        "shelled out for a headliner who forgot lyrics",
        "called a superstar’s bluff and lost the house",
        "built a palace of red questionables",
        "paid for ceiling, got crawlspace",
        "invested in fumes and collected soot",
        "rolled out VIP tags on JV output",
    ],
    # Pools
    "survivor": [
        "rode the chalk bus with the emergency brake on",
        "kept the survivor streak alive with bubble wrap",
        "picked the least adventurous postcard on the rack",
        "trusted their pool life to point spreads and vibes",
        "kept the lifeline afloat with duct tape",
        "is still dodging land mines with ballet slippers",
        "brought a hard hat and a prayer to the survivor site",
        "let implied odds babysit their pick",
        "whispered sweet nothings to the moneyline",
        "caressed the safest matchup like a therapy pet",
        "treated survivor like a corporate wellness plan",
        "keeps the lifeboat patched with waiver wire gum",
    ],
    "confidence": [
        "stacked confidence picks like a Jenga tower in wind",
        "pinned their hopes on the top seed’s Airbnb",
        "ranked games by jersey color and vibes",
        "treated confidence like a credit score—barely",
        "played roulette with tiebreakers and lived",
        "made boldness a spectator sport",
        "borrowed swagger from a Vegas forecast",
        "cuffed their top pick to the safest favorite",
        "sprinkled upset pixie dust with a shaky hand",
        "is rationing swagger like playoff tickets",
        "keeps the pool entry afloat with duct-taped logic",
        "outsourced conviction to the betting market",
    ],
    # Generic fallback lines
    "generic": [
        "left fingerprints all over the league chat",
        "turned Sunday into a content warning",
        "is begging variance for a restraining order",
        "makes the waiver wire ask for hazard pay",
        "left their dignity in the projection model",
        "treats momentum like a rumor",
        "tried to rent a parade float and got declined",
        "has the advanced metrics hiding under the bed",
        "needs a burner account just to process this week",
        "refreshes the app like it owes them gas money",
        "is rewriting the how-not-to manual in real time",
        "made the league commissioner start a wellness check",
        "asks Siri for lineup advice mid-collapse",
        "has Amazon sending sympathy deliveries",
        "turned the waiver wire into a true crime scene",
        "brought spreadsheets to a bar fight and lost",
        "made the recap podcast issue a parental advisory",
        "is shopping for excuses on the clearance rack",
        "set the vibes to airplane mode",
        "has their fan club filing a missing-person report",
    ],
}

__all__ = ["PHRASE_BANK"]
