name: NPFFL Weekly Newsletter

on:
  workflow_dispatch:
    inputs:
      week:
        description: "Week number (1-18). Leave blank to auto-select last completed week."
        required: false
        default: ""
  schedule:
    - cron: "0 16 * * 2"  # Tuesday 12:00 PM ET (EDT). Change to 17:00 after DST.

permissions:
  contents: read

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure env
      env:
        MFL_USERNAME: ${{ secrets.MFL_USERNAME }}
        MFL_PASSWORD: ${{ secrets.MFL_PASSWORD }}
        MFL_API_KEY: ${{ secrets.MFL_API_KEY }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "MFL_USERNAME=${MFL_USERNAME}" >> $GITHUB_ENV
        echo "MFL_PASSWORD=${MFL_PASSWORD}" >> $GITHUB_ENV
        echo "MFL_API_KEY=${MFL_API_KEY}"   >> $GITHUB_ENV
        echo "SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}" >> $GITHUB_ENV

    - name: Run newsletter
      env:
        WEEK: ${{ github.event.inputs.week }}
      run: |
        python -m src.main --week "${WEEK}" env
        env:
          MFL_USERNAME: ${{ secrets.MFL_USERNAME }}
          MFL_PASSWORD: ${{ secrets.MFL_PASSWORD }}
          MFL_API_KEY: ${{ secrets.MFL_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "MFL_USERNAME=${MFL_USERNAME}" >> $GITHUB_ENV
          echo "MFL_PASSWORD=${MFL_PASSWORD}" >> $GITHUB_ENV
          echo "MFL_API_KEY=${MFL_API_KEY}"   >> $GITHUB_ENV
          echo "SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}" >> $GITHUB_ENV

      - name: Run newsletter
        env:
          WEEK: ${{ github.event.inputs.week }}
        run: |
          python -m src.main --week "${WEEK}"
