name: NPFFL Weekly Newsletter

on:
  workflow_dispatch:
    inputs:
      week:
        description: "Week number (1-18). Leave blank to auto-select last completed week."
        required: false
        default: ""
  schedule:
    - cron: "0 16 * * 2"  # Tuesdays 12:00 PM ET (EDT)

permissions:
  contents: read

jobs:
  build-newsletter:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Ensure requirements
        run: |
          set -euo pipefail
          if [ ! -f requirements.txt ]; then
            cat > requirements.txt <<'REQ'
pandas>=2.2
requests>=2.32
PyYAML>=6.0
openpyxl>=3.1
python-dateutil>=2.9
jinja2>=3.1
markdown>=3.6
beautifulsoup4>=4.12
lxml>=5.2
rapidfuzz>=3.7
REQ
          else
            # make sure critical deps exist
            for pkg in pandas requests PyYAML openpyxl python-dateutil jinja2 markdown beautifulsoup4 lxml rapidfuzz; do
              grep -iE "^\s*$pkg\b" requirements.txt >/dev/null || echo "$pkg" >> requirements.txt
            done
